### ISSUE TITLE
Fails to get devices

### ISSUE THREAD

**Issue by PasiSalenius** [valiquette/homebridge-easee#16]
For some reason this plugin cannot load devices after signing into my account. It doesn't seem to proceed after this error and I cannot see the charger in my Home app.

I can only see the following error message in the log output of Homebridge:

`[Easee] Failed to get devices. Retry attempt 1 of 3 in 60 seconds...`

**Comment by valiquette** [comment]
Can you please attach debug log during the the start up?

**Comment by PasiSalenius** [comment]
How do I get that debug log?

**Comment by PasiSalenius** [comment]
Okay this probably includes the relevant parts, I obfuscated some of the details:

```
[31/07/2023, 18:23:35] [Easee] Retrieving profile info of logged in account
[31/07/2023, 18:23:36] [Easee] get user response {
  "userId": 740017,
  "eMail": "xxxxxxxxx@gmail.com",
  "phoneNo": "+358xxxxxxxxx",
  "firstName": "Pasi",
  "lastName": "Salenius",
  "street": "Xxxxxxxxx 123 A",
  "zipCode": "12345",
  "city": "Tampere",
  "country": "Finland",
  "countryId": "FI",
  "language": "fi",
  "emailVerified": true,
  "subscribeNewProductUpdate": true,
  "subscribeProductUpdate": true,
  "company": null,
  "isActive": true
}
[31/07/2023, 18:23:36] [Easee] Found account for Pasi Salenius
[31/07/2023, 18:23:36] [Easee] Retrieving products of logged in account
[31/07/2023, 18:23:36] [Easee] get products data response [
  {
    "id": 123456,
    "siteKey": "AAAA-1234",
    "name": "Xxxxxxxxx 123 A",
    "levelOfAccess": 1,
    "address": null,
    "siteType": 1,
    "ratedCurrent": 25,
    "partnerId": 20,
    "circuits": [
      {
        "id": 123456,
        "siteId": 123456,
        "circuitPanelId": 1,
        "panelName": "1",
        "ratedCurrent": 16,
        "chargers": [
          {
            "id": "ECV7T123",
            "name": "Easee Home",
            "levelOfAccess": 1,
            "userRole": 1,
            "productCode": 100,
            "backPlate": {
              "id": "xxxxxxxxxxxxxxxxxx",
              "masterBackPlateId": "xxxxxxxxxxxxxxxxxx",
              "name": null
            },
            "isTemporary": false,
            "color": 1,
            "createdOn": "2022-07-04T08:00:40.580586",
            "updatedOn": "2023-07-18T14:10:35.446351"
          }
        ],
        "masterBackplate": null,
        "useDynamicMaster": false,
        "parentCircuitId": null
      }
    ],
    "equalizers": [],
    "userRole": 1,
    "allowedSiteActions": [
      "AllowToConfigureLevelOfAccess"
    ]
  }
]
[31/07/2023, 18:23:36] [Easee] Failed to get devices. Retry attempt 3 of 3 in 60 seconds...
```

**Comment by valiquette** [comment]
After the 3rd try do you see an error message?

**Comment by PasiSalenius** [comment]
Ah yes, sorry that I left it out:

```
[31/07/2023, 18:24:37] [Easee] Failed to get devices...
TypeError: Cannot read properties of null (reading 'street')
    at /var/lib/homebridge/node_modules/homebridge-easee/easeeplatform.js:111:63
    at Array.filter (<anonymous>)
    at easeePlatform.getDevices (/var/lib/homebridge/node_modules/homebridge-easee/easeeplatform.js:110:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by PasiSalenius** [comment]
Ah I just noticed that the street address details were incomplete in easee.cloud portal. Filled them in and now it seems to work! 👍

**Comment by valiquette** [comment]
Thanks, I will look at adding some messaging for that use case.

**Comment by kempd** [comment]
Hi

I got a message from Easee asking wether they could save my address information as it was optional information. 
I choose to remove it from my profile. 

This causes the plugin to break, and results in the devices not being found in my profile.

Best regards.

**Comment by valiquette** [comment]
Just remove the address in the plugin config. If it is blank then it should load all locations.

**Comment by kempd** [comment]
The address field is already blank.

**Comment by valiquette** [comment]
Try deleting the line from the config.

**Comment by kempd** [comment]
locationAddress wasn't in there either. I added  a dummy value and changed the json value to the following.

```
 "locationAddress": "",
```

I'll try to test if this resolves it, tomorrow.

**Comment by valiquette** [comment]
Being null is all it needs, if it is still an issue let me know, I made some changes in that area, but never published because I could not test it.

**Comment by kempd** [comment]
Unfortunately, it's not working without the location info.

```
[12/31/2023, 4:54:23 PM] Homebridge v1.7.0 (HAP v0.11.1) (Easee) is running on port 59406.
[12/31/2023, 4:54:24 PM] [Easee] Found account for 
[12/31/2023, 4:54:24 PM] [Easee] Failed to get devices. Retry attempt 1 of 3 in 60 seconds...

[12/31/2023, 4:57:25 PM] [Easee] Getting Account info...
[12/31/2023, 4:57:25 PM] [Easee] Found account for
[12/31/2023, 4:57:26 PM] [Easee] Failed to get devices...
TypeError: Cannot read properties of null (reading 'street')
    at /homebridge/node_modules/homebridge-easee/easeeplatform.js:111:63
    at Array.filter (<anonymous>)
    at easeePlatform.getDevices (/homebridge/node_modules/homebridge-easee/easeeplatform.js:110:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

Is still what I get.

I did set an empty location value in the config manually, but it seems to get removed (property and value) automatically when restarting the child bridge. In the UI, location is empty however.

**Comment by valiquette** [comment]
Got it, that is something I have already addressed, but I will not be able to publish the update for this for a day or two due to traveling. The API response from Easee is missing that field so it fails with nothing to check against.

**Comment by valiquette** [comment]
I published v1.2.4-test.1 Which I believe will address your issue, but I cannot test it. 
Please let me know if it works.

**Comment by kempd** [comment]
Fetching the Charger and Loadbalancer works again. 
Looks good, 

I didn't had the chance yet to test functionality however. 

```
[1/3/2024, 1:37:08 PM] Homebridge v1.7.0 (HAP v0.11.1) (Easee) is running on port 59406.
[1/3/2024, 1:37:09 PM] [Easee] Found account for <name>
[1/3/2024, 1:37:09 PM] [Easee] Found products at undefined location <name>
[1/3/2024, 1:37:09 PM] [Easee] Adding <name> found at the configured location: undefined location
[1/3/2024, 1:37:09 PM] [Easee] Found charger <id> with ID-<id> 
[1/3/2024, 1:37:09 PM] [Easee] Circuit ID <id> Site ID-<id> 
[1/3/2024, 1:37:09 PM] [Easee] Adding Lock for <id> charger 
[1/3/2024, 1:37:09 PM] [Easee] Configured Lock for <id>
[1/3/2024, 1:37:09 PM] [Easee] Configured <id> Pause/Resume outlet for <id>
[1/3/2024, 1:37:09 PM] [Easee] Adding Charger Lock for <id>
[1/3/2024, 1:37:09 PM] [Easee] Adding Equalizer <id> for site ID <id>
[1/3/2024, 1:37:09 PM] [Easee] Configured Equalizer for <id>
[1/3/2024, 1:37:09 PM] [Easee] Adding Equalizer <id>
[1/3/2024, 1:37:09 PM] [Easee] Starting connection for live updates...
[1/3/2024, 1:37:09 PM] [Easee] <id> cable lock state to true
[1/3/2024, 1:37:09 PM] [Easee] <id> updated to ChargerOpMode Disconnected
[1/3/2024, 1:37:09 PM] [Easee] <id> disconnected
[1/3/2024, 1:37:09 PM] [Easee] <id> OutputCurrent updated to 0
[1/3/2024, 1:37:09 PM] [Easee] <id> DynamicChargerCurrent updated to 32
[1/3/2024, 1:37:09 PM] [Easee] <id> ReasonForNoCurrent due to SecondaryUnitNotRequestingCurrent
[1/3/2024, 1:37:09 PM] [Easee] <id> AuthorizationRequired updated to true
[1/3/2024, 1:37:09 PM] [Easee] <id> MaxChargerCurrent updated to 32
[1/3/2024, 1:37:09 PM] [Easee] <id> offline reason 0
[1/3/2024, 1:37:14 PM] [Easee] Easee Platform finished loading
```

**Comment by kempd** [comment]
It's all working again 😃
Thank you!
