### ISSUE TITLE
Humitity stays at 0%

### ISSUE THREAD

**Issue by Hedgepigthe1st** [valiquette/homebridge-easee#17]
No matter how I start the charge manually or through the plug-in the status never changes to charging and the humidity stays at 0%.

it also seems to be over clocking my cpu to 100% on my raspberry pi when sending some requests through to the easee but not sure if that’s the reason or something else.

but absolutely love it never thought I’d be able to control my charger through homekit!

**Comment by valiquette** [comment]
The characteristic for humidity is not something that is used so it showing as 0%. As far as the status to charging not updating. I would need debug logs to look at that.

**Comment by Hedgepigthe1st** [comment]
![IMG_6586](https://github.com/valiquette/homebridge-easee/assets/141939572/8827c5a7-eb4c-4844-a7ea-6b55d9322562)


No worries I read this as would create humorists sensor showing battery level.

mum new to homebridge how do I get you those debug logs? Thanks

**Comment by valiquette** [comment]
Sorry, you're correct, forgot that was there. I don't actually own a device to test with but it mirrors another plugin. If you can send me the debug log I can take a look. In homebridge setting you can enable debug logging then in the Easee plugin you can go to extra login and show the observation messages. Also could you send me a copy of you config.

Does this also show a 0% in homebridge?

**Comment by Hedgepigthe1st** [comment]
it does show 0% in Homebridge. hope this is what you need? again first time doing this 😀

[homebridge.log.txt](https://github.com/valiquette/homebridge-easee/files/12411738/homebridge.log.txt)

  "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Easee",
            "username": "unknown*",
            "password": "unknown",
            "cars": [
                {
                    "carName": "Zelda",
                    "kwH": 73
                }
            ],
            "showControls": 3,
            "showLight": false,
            "useOutlet": false,
            "showReboot": false,
            "showOverride": false,
            "socSensor": false,
            "showEqualizer": false,
            "showSignalRMessages": true,
            "showAPIMessages": false,
            "experimental": false,
            "eqMin": 15,
            "eqMax": 100,
            "platform": "easee"
        }
    ]
}

**Comment by imangineer** [comment]
I have the same problem. I get this error in the log:

Failed to update battery. 
TypeError: Cannot read properties of undefined (reading 'includes')
    at /var/lib/homebridge/node_modules/homebridge-easee/easeeplatform.js:338:60
    at Array.filter (<anonymous>)
    at easeePlatform.calcBattery (/var/lib/homebridge/node_modules/homebridge-easee/easeeplatform.js:338:23)
    at easeePlatform.updateService (/var/lib/homebridge/node_modules/homebridge-easee/easeeplatform.js:618:52)
    at HubConnection.<anonymous> (/var/lib/homebridge/node_modules/homebridge-easee/easeeapi.js:778:18)
    at HubConnection._invokeClientMethod (/var/lib/homebridge/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:707:31)
    at HubConnection._processIncomingData (/var/lib/homebridge/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:555:30)
    at WebSocketTransport.HubConnection.connection.onreceive (/var/lib/homebridge/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:113:57)
    at WebSocket.webSocket.onmessage (/var/lib/homebridge/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/WebSocketTransport.ts:111:30)
    at WebSocket.onMessage (/var/lib/homebridge/node_modules/homebridge-easee/node_modules/ws/lib/event-target.js:132:16)

**Comment by imangineer** [comment]
The error message indicates that the chargerName property is undefined in at least one of the items in the this.cars array. This causes the error when trying to access the includes method on charger.chargerName.
